# Database Configuration
database:
  host: "127.0.0.1"
  port: 3306
  database: "mc_beefantasy_m1_mysql"
  username: "minecraft"
  password: "123456789"

# Custom Messages
messages:
  # The message shown to players who are banned.
  # %duration% will be replaced with the duration of the ban.
  # %reason% will be replaced with the reason for the ban.
  banMessage: "You are banned for %duration%. Reason: %reason%"

  # The message shown to the command sender when a player is banned.
  # %player% will be replaced with the name of the banned player.
  playerBannedNotification: "Player %player% has been banned."

  # The message shown to the command sender when a player is unbanned.
  # %player% will be replaced with the name of the unbanned player.
  unbanMessage: "Player %player% has been unbanned."

  # The message shown to players who try to join but are banned.
  # %reason% will be replaced with the reason for the ban.
  kickMessage: "You cannot join this server. Reason: %reason%"

# History GUI Configuration
historyGUI:
  # Prefix for the GUI title
  titlePrefix: "Ban History: Page "

  # Number of entries shown per page
  itemsPerPage: 45
